### PR TITLE
Update ML.txt

### PR DESCRIPTION
**Pull request by WillBeInfluentialProgrammer**

### CODE REVIEW

**Comment by TouseefDataScientist** [comment]
Your file name is ML.text?
So please you you will try Desktop version and then drag and drop.

**Comment by WillBeInfluentialProgrammer** [comment]
project proposal

**Comment by WillBeInfluentialProgrammer** [comment]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by WillBeInfluentialProgrammer** [comment]
---------- Forwarded message ---------
From: Tashfeen Mehmood ***@***.***>
Date: Fri, Sep 6, 2024, 12:55 AM
Subject: Fwd: Competition Launch: UM - Game-Playing Strength of MCTS
Variants
To: ***@***.*** ***@***.***>



---------- Forwarded message ---------
From: Kaggle ***@***.***>
Date: Thu, Sep 5, 2024, 11:21 PM
Subject: Competition Launch: UM - Game-Playing Strength of MCTS Variants
To: ***@***.***>


[image: Kaggle]

Hi Tashfeen Mehmood,

Monte-Carlo tree search (MCTS) is a search algorithm used to create agents
that play board games intelligently. Researchers have proposed dozens, if
not hundreds, of MCTS variants over the last 20 years - but it’s still
challenging to determine which variants are best suited for specific types
of games.

In this competition hosted by Maastricht University, you’ll create a model
to predict how well one MCTS variant will do against another in a given
game.
Total Prizes:

$50,000
Entry Deadline:

November 25, 2024
Learn More
<https://notifications.google.com/g/p/ANiao5q0PqLTraaZrqwXislbdBL1YyxfS47dYJDCPji9AR6iMGLvEztI1xi8jqKIbT4z4QcusGQieM9uDOhXMwfU5A7-O4WBbNMTF_qvxCR_HtlgRwqEsTP-80hL0G8e_dtAwF_Fg9CQXOWYERfTRgP1cwelRUlEPtu8OM457MtrsMG4julgP4pZxP-QO9MpTJZi-JubxuUPDX026wM0hgd2OBjcBdkDTpIu9pYKxrrxS7qW43LiQGZ8MzYGfTip7hMu-xI2hXiMTLgRMvEfmy3_gtaKwYTCZCRVNTew86jRJnTjbirshjVzzlDu1qcFTRswQdiqR0tcXnWvMfWEfqT_LqzVFTagBC0vt3afQ47qs3cl>

Your work could help pave the way for identifying the strengths and
weaknesses of different MCTS variants, advancing our understanding of where
they work best in various scenarios.

Good luck,

Walter Reade
Kaggle Data Scientist

Kaggle, Inc 1600 Amphitheatre Pkwy Mountain View, CA 94043
<https://www.google.com/maps/search/1600+Amphitheatre+Pkwy+Mountain+View,+CA%0D%0A++++++++++++++++++++++++94043?entry=gmail&source=g>

This email was sent to ***@***.*** because you indicated that
you'd like to receive news and updates about Kaggle. If you don't want to
receive these emails in the future, please unsubscribe here
<https://notifications.google.com/g/p/ANiao5pSqEwpMktYDPx9NedDz5qzU3Ybf2wXcrBXbS1RDHfPW_fEgyj949DG5Cok2QlPh0oWoiXjuwbXPvZek7ldWDwebvvtF2PWHf8IW4EAA7enDwyCdJo9kJTjzS53zViDCvimJY3JSFJqR7ykrdm0FbfAi3yU8cWjNzza8xoa1ls3FpRVvir1uXiFSYx88iWaY9ticD64xPg9vr6zEoceaYCIkC34KvmNCaD90QwhCwEhDGFyhdjkpYaRHkHaAZ9aWUOPjIudjDQQ6jOZ5n46L53tDX8kzgNXh6CjKBgn4yCWyYIvMedI>.
You can also change your preferences on your account's profile page by
logging in at kaggle.com.
<https://notifications.google.com/g/p/ANiao5q36jvFuLFXjrCDeNAuSEm_ECI5CDymAH9HYanWTp2QduTZfQf79jBB4kt6_HNSSfAxtlNouJseOypCeBHmH0-0jMr4sNXVx9NZAvgB07m2J0siWptRODT_qdB-qIk1cpWrP04GUMwUC3AblI-uPiZeRB_1CtaKnXf__i47Xj7pN_TcpBxs6ySrGIw9x2-tnFLrBR8N1DyTRus>

**Pull request closed without merging**
